import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/store/StoreProvider";
import GoogleAuthProvider from "@/components/custom/GoogleAuthProvider";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/providers/AuthProvider";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "InterPract",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const cookieData = cookieStore.get("session");

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <StoreProvider>
          <GoogleAuthProvider>
            <AuthProvider cookieData={cookieData?.value}>
              {" "}
              {children}{" "}
            </AuthProvider>
          </GoogleAuthProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
